### ISSUE TITLE
Einbindung

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/rrze-univis#1]
Welche Shortcodes o. ä. muss ich verwenden, um Univis-Daten importieren zu können?

**Comment by endv02** [comment]
Aktuell geht nur folgender Shortcode:
- [univis]:
Anzeige eines Links zur UnivIS-Startseite, der Linktext kann unter Einstellungen - UnivIS modifiziert werden
- [univis number="1005681200"]:
Bindet das Organigramm der Organisationseinheit mit der UnivISOrgNr 1005681200 ein

**Comment by cibsell** [comment]
Danke für den Hinweis!

Ich habe aber noch eine Frage: werden die Einträge nicht alphabetisch angezeigt? 

Wenn ich in Univis mir eine Institution anzeigen lasse, z. B. Lehrstuhl für Organische Chemie I ( http://univis.fau.de/form?__s=2&dsc=anew/tel&dir=nat/dchph/loc1&anonymous=1&ref=tel&sem=2015s&__e=483 , Link wird wohl nicht mehr gehen...), dann werden die Personen alphabetisch aufgeführt. 

Wenn ich über das Univis-Plugin die Einrichtung anzeigen lasse, werden die Personen nicht alphabetisch angezeigt: http://chem.nat.fau.de/department/personen-a-z/ 

Wie kann ich diese Einträge alphabetisch sortieren?
