### ISSUE TITLE
Ausgabe auf der Beta.wordpress-Seite

### ISSUE THREAD

**Issue by ej64ojyw** [RRZE-Webteam/rrze-univis#106]
Ich weiß nicht ob das ein Bug ist, oder ob die Ausgabe da mit was anderem noch Zusammenhängt:

https://www.beta.wordpress.rrze.fau.de/plugins/rrze-univis/
Hier sehe ich keine Ausgabe bei den Shortcodes.

![grafik](https://user-images.githubusercontent.com/58593037/116514134-e5f79400-a8ca-11eb-8b6b-f8899036d5a6.png)

Wenn man Sie aber gesondert auf einer neuen Testseite einzeln einfügt passt alles perfekt und sieht perfekt aus:
https://www.beta.wordpress.rrze.fau.de/testseite-29042021/

![grafik](https://user-images.githubusercontent.com/58593037/116514107-d8420e80-a8ca-11eb-9816-261a3b812d47.png)

**Comment by ej64ojyw** [comment]
Das Problem tritt auch auf der Doku-Seite auf:
https://www.wordpress.rrze.fau.de/plugins/fau-und-rrze-plugins/rrze-univis/publikationsdaten-einbinden/

![grafik](https://user-images.githubusercontent.com/58593037/116518423-80a6a180-a8d0-11eb-8b6c-e4c048ca524c.png)

**Comment by thenickless** [comment]
gefixt in 3.2.18
