### ISSUE TITLE
"Nach oben"-Links wirkungslos

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/rrze-univis#11]
Beim Erzeugen einer Mitarbeiterliste aus UnivIS sind jeweils Ankerlinks "nach oben", die keinerlei Auswirkung haben. Screenshot:

![univis_plugin_liste](https://cloud.githubusercontent.com/assets/11296947/11400866/019b86c2-9390-11e5-9d59-a22d8620e117.png)

**Comment by AstridSemm** [comment]
Bei der Durchsicht meiner Issues festgestellt, dass das immer noch so ist. Der Anker zeigt auf #seitenmarke, die id scheint aber nicht zu exisiteren. Auch bei sehr langen Listen (ich habe es jetzt mit der kompletten Mitarbeiterliste des Dept. Maschinenbau getestet) hat der Link keinerlei Wirkung. Bitte mal draufschauen, das verwirrt ja eigentlich nur.

**Comment by endv02** [comment]
Ist ab der Version 2.1.4 korrigiert, der nach oben-Link ist weg.
