### ISSUE TITLE
Ausgabe von Lehrveranstaltungen

### ISSUE THREAD

**Issue by Joelx** [RRZE-Webteam/rrze-univis#12]
Hallo RRZE-Webteam,
ist die Verwendung des "lehrveranstaltungen-einzeln" Attributs, sowie von Filter- und Sortierfuntionen für die Lehrveranstaltungen schon möglich? 
Im Repo sind die Controller hierfür schon enthalten. Es gelingt mir aber nur die Ausgabe aller Einträge beginnend mit "Sonstigen Lehrveranstaltungen".

Wäre schön, wenn Sie sich das mal angucken könnten :)

**Comment by Joelx** [comment]
Gibt es hierfür inzwischen eine Möglichkeit?
Genauer gesagt bräuchten wir einen Weg, Einträge wie Lehrveranstaltungen und studentische Arbeiten direkt aus dem UniVis in die Seite einzupflegen, sodass etwaige Änderungen direkt aktualisiert werden.
Da wir bald mit der Website online gehen möchten, würde ich mich sehr über Rückmeldung freuen.

**Comment by endv02** [comment]
Waren jetzt mit dem Webkongress gut beschäftigt, mache mich jetzt aber gleich dran und gebe dann Bescheid.

**Comment by Joelx** [comment]
Vielen Dank :)

**Comment by endv02** [comment]
Lehrveranstaltungen können jetzt über den task "lehrveranstaltungen-einzeln" mit der ID eingebunden werden. Die Lehrveranstaltungen einer einzelnen Person mit task="lehrveranstaltungen-alle" und mit dozentenid="..." oder dozentenname="nachname,vorname" der Person. Außerdem noch einzelne Mitarbeiter über den task "mitarbeiter-einzeln" mit firstname="Vorname" lastname="Nachname" der Person. Wenn noch was fehlen sollte, bitte einfach melden! (Genaueres in der readme)
