### ISSUE TITLE
Semesterauswahl optional

### ISSUE THREAD

**Issue by endv02** [RRZE-Webteam/rrze-univis#13]
In Einstellungen - UnivIS muss optional auswählbar sein, welches Semester angezeigt werden soll (Lehrveranstaltungen). Jetzt ist es abhängig von der Umstellung der UnivIS-Seite.

**Comment by sistlind** [comment]
Das sollte nicht in den Einstellungen eingestellt werden können, sondern im Shortcode, sonst kann man nicht verschiedene Semester anzeigen.
Wie zB hier: https://lte.techfak.uni-erlangen.de/teaching/ (Links im menü) oder hier: https://lte.techfak.uni-erlangen.de/person/robert_weigel/

**Comment by endv02** [comment]
siehe auch #26

**Comment by endv02** [comment]
Ist ab Version 1.3.1 im Shortcode mit drin.
