### ISSUE TITLE
Einbindung einer Lehrveranstaltung via ID funktioniert nicht

### ISSUE THREAD

**Issue by csw-** [RRZE-Webteam/rrze-univis#15]
Ich möchte eine einzelne Lehrveranstaltung einbinden, bekomme aber den Fehlertext "Bitte geben Sie einen Vor- und Nachnamen an."
Übersehe ich hier etwas?

Man darf sich gerne hier austoben: [https://institut-marketing.cms.rrze.uni-erlangen.de/studium/veranstaltungen/](https://institut-marketing.cms.rrze.uni-erlangen.de/studium/veranstaltungen/)

Org: Lehrstuhl für Betriebswirtschaftslehre, insbesondere Versicherungsmarketing (Stiftungslehrstuhl) 
Org-Info: [http://vorlagen.uni-erlangen.de/anwendungen/univis/suche-einrichtungen.shtml?doform=1&suche=versicherungsmarketing#](http://vorlagen.uni-erlangen.de/anwendungen/univis/suche-einrichtungen.shtml?doform=1&suche=versicherungsmarketing#)
OrgNr: 1212002600

Lv: Seminar zur Bachelorarbeit
Lv-Url: [http://univis.uni-erlangen.de/prg?search=lectures&id=20985193&show=long](http://univis.uni-erlangen.de/prg?search=lectures&id=20985193&show=long)
Lv-ID: 20985193

Shortcode: [univis task="lehrveranstaltungen-einzeln" id="20985193"]
Univis-Einstellungen: OrgNr 1212002600

Alternativ:  [univis number="1212002600" task="lehrveranstaltungen-einzeln" id="20985193"]

**Comment by csw-** [comment]
Noch eine andere Frage: Wie kommt man denn am schnellsten an die ID einer Lehrveranstaltung? 

Über Univis selbst bin ich nicht fündig geworden, also habe ich mich der LV-Links bedient, die man durch die Verwendung des Tasks "lehrveranstaltungen-alle" erhält. Hier steckt die ID dann ja jeweils in der URL.

Für einen normalen Editor/Redakteur ist das aber ein sehr aufwändiges Unterfangen XD

**Comment by endv02** [comment]
Danke für den Hinweis, da war tatsächlich ein Bug versteckt. Ist behoben mit Version 1.2.2

**Comment by endv02** [comment]
Zur Suche nach der LV-ID: 
ja, tatsächlich ist das auch die Methode, mit der ich die ID raussuche. Ob man beim Eingeben der LV in UnivIS leichter die ID finden kann, kann ich leider nicht beurteilen.
