### ISSUE TITLE
Lehrveranstaltungen mit Type "UE" gibt auch Vorlesungen aus

### ISSUE THREAD

**Issue by Blubbaa** [RRZE-Webteam/rrze-univis#150]
Folgender Shortcode gibt zusätzlich zu den Übungen (UE) auch (verknüpfte?) Vorlesungen (VORL) aus:
`[univis task="lehrveranstaltungen-alle" type="ue" lv_import="0" parent_lv="0" hide="lv-typ,ics"]`

**Comment by thenickless** [comment]
Vielen Dank für den Hinweis! Da die UnivIS-Schnittstelle derzeit nicht korrekt nach Type filtert, wurde das UnivIS-Team informiert. Ich melde mich hier umgehend, sobald das Problem behoben wurde.

**Comment by thenickless** [comment]
In Version 3.2.63 ist ein Quickfix eingebaut, da auf Seiten von UnivIS der Fehler noch nicht behoben wurde. 

Falls Sie das gewünschte Ergebnis nicht unmittelbar sehen, dann schafft das Attribut nocache Abhilfe:

[univis task="lehrveranstaltungen-alle" type="ue" lv_import="0" parent_lv="0" hide="lv-typ,ics" nocache="1"]

Zur Verbesserung der Performance ist im Plugin ein Cache eingebaut. Mit diesem Attribut wird er deaktiviert. Löschen Sie das Attribut anschließend wieder, damit es nicht zu unnötigen Ladeverzögerungen kommt:

[univis task="lehrveranstaltungen-alle" type="ue" lv_import="0" parent_lv="0" hide="lv-typ,ics"]
