### ISSUE TITLE
lang-Attribut hat keine Auswirkung

### ISSUE THREAD

**Issue by TFWebm** [RRZE-Webteam/rrze-univis#152]
Das lang-Attribut hat keine Auswirkung:
`[univis task="lehrveranstaltungen-alle" sprache="E"]`
Liefert alle Vorlesungen der Org-Einheit. Der Fehler scheint hier schon auf Seiten von UnivIS zu liegen, da
[https://univis.fau.de/prg?show=json&search=lectures&lang=E&department=100100](https://univis.fau.de/prg?show=json&search=lectures&lang=E&department=100100)
die selben Daten liefert.

**Comment by thenickless** [comment]
Vielen Dank für den Hinweis! Sie haben recht - auch die UnivIS-Schnittstelle filtert nicht mehr korrekt. Ich habe das UnivIS-Team kontaktiert und werde Sie hier informieren, sobald der Fehler behoben ist.

**Comment by thenickless** [comment]
Vielen Dank für die Geduld. In Version 3.2.61 ist ein Quickfix eingebaut, da auf Seiten von UnivIS der Fehler noch nicht behoben wurde.
