### ISSUE TITLE
Berechtigungs-Bug beim Anzeigen von Bildern

### ISSUE THREAD

**Issue by FloPro666** [RRZE-Webteam/rrze-univis#154]
Hallo,

manche Bilder von Kontakten, bei denen die Checkbox 'Zugriffsschutz' ausgewählt ist sowie die Berechtigung auf 'Alle' gestellt ist, werden trotzdem auf unserer Webseite nicht angezeigt. Wenn man den Haken herausnimmt, werden sie wieder angezeigt. Als Beispiel hier das Profil von einem Kollegen: 

https://www.lte.tf.fau.de/person/christopher-beck/

Liebe Grüße
Florian

**Comment by thenickless** [comment]
Hallo Florian, Danke für den Hinweis! Der Bug wird nicht vom rrze-univis ausgelöst, sondern vermutlich von "RRZE Access Control" und ist nun dort als Issue eingetragen: https://gitlab.rrze.fau.de/rrze-webteam/rrze-ac/-/issues/10
