### ISSUE TITLE
Lehrveranstaltungen tauchen mehrfach auf wenn mehreren Studiengängen zugeordnet

### ISSUE THREAD

**Issue by endv02** [RRZE-Webteam/rrze-univis#17]
Gewünschte Lösungsansätze Phil-Fak:
Am liebsten wäre uns ein Schalter, der es ermöglicht, LV nach Organisationseinheit (Lehrstuhl) oder auch nach Studiengang aufzulisten. Auf diese Art wäre es möglich, Überblickslisten der LV je nach Verwendungszweck zu generieren. Bei der Generierung der Lehrstuhllisten sollte dabei jede LV nur einmal vorkommen, also Duplikate gefiltert werden.
Wenn wir uns entscheiden müssten, wäre uns die Anzeige der LV nach Lehrstuhl wichtiger als die Anzeige nach Studiengängen.

**Comment by AstridSemm** [comment]
Danach haben die Kollegen in der Anglistik mich gestern auch gefragt. Als Beispiel mal diese Seite: https://anglistik.cms.rrze.uni-erlangen.de/fields_of_study/american-studies/american-studies-literature/teaching/
Bonusfrage: Wie kommen die Überschriften zustande? Sind die so in univis eingepflegt oder macht das das Plugin?

**Comment by endv02** [comment]
Erste Bonusfrage: drin ab Version 1.2.5, die Abkürzungen sind in UnivIS eingepflegt, den "schönen" Text macht das Plugin

**Comment by endv02** [comment]
Hm... es eine professionelle Übersetzung für die Lehrveranstaltungsarten gäbe, könnte man die auch einpflegen...

**Comment by thenickless** [comment]
Nicht für Version 3 relevant.
