### ISSUE TITLE
Einbindung von Organisationen: Englische Gruppenbezeichnungen möglich?

### ISSUE THREAD

**Issue by csw-** [RRZE-Webteam/rrze-univis#18]
Mir ist aufgefallen, dass die Gruppenbezeichnungen in UnivIS lediglich in deutscher Sprache vorhanden sind. Gibt es überhaupt eine Möglichkeit in UnivIS auch englische Bezeichnungen dafür zu hinterlegen? 
(Als Workaround könnte man ja vllt ein dictionary für die gängigsten Gruppenbezeichnungen hinterlegen...)

![univis_org_en](https://cloud.githubusercontent.com/assets/6545158/17836187/37b201fa-6789-11e6-804f-28e2eb15081d.png)

**Comment by csw-** [comment]
Habe mittlerweile von dem Univis-Team erfahren, dass man durchaus englische Begriffe hinterlegen kann.  Hier müssten also auch erstmal die Univs-Betreuer entsprechend aktiviert werden auch die englischen Einträge zu pflegen.

**Comment by endv02** [comment]
Ja, das wurde kurz vor meinem Urlaub dann endlich in UnivIS eingebunden. Bin aber erst jetzt wieder da und kann mich um die Einbindung kümmern und testen.

**Comment by endv02** [comment]
Moment mal... von UnivIS bekomme ich über xml die englischen Bezeichnungen für orgname und orgunits geliefert, aber nicht die englischen Bezeichnungen für Leitung, Sekretariat etc... Aber die Webredaktion hat ähnliche Wünsche gehabt und diesbezüglich Interesse gezeigt, eine einheitliche Regelung herbeizuführen...

**Comment by endv02** [comment]
Mit der neuesten Version wird die Gruppenbezeichnung auch auf englisch ausgegeben, wenn
1. die Webseitensprache in den Einstellungen auf englisch eingestellt ist und
2. diese auch mit eingepflegt sind.
Letzteres ist vermutlich Sache der UnivIS-Bebetreuer, da meiner Beobachtung nach nicht in jedem Webauftritt vorhanden.
