### ISSUE TITLE
Raumnummer einzeln verfügbar machen

### ISSUE THREAD

**Issue by H6pOJTyp** [RRZE-Webteam/rrze-univis#184]
Vielen Dank für das Plugin, wir nutzen das an diversen Stellen unserer Web-Präsenz an der FAU.
Wärs möglich, als Alternative zur kompletten Adresse, die Raumnummer einzeln verfügbar zu machen?
Wenn man z.b. eine Mitarbeiterliste erzeugt, und dann für Dutzende von Leuten jedesmal die selbe,
noch dazu recht lange, Postadresse anzeigt, in der die Raumnummer das einzige Detail ist, das
die Zeilen unterscheidet, dann wird das recht unübersichtlich.  Cool wärs sowas wie
 ```Name  | Emailadresse | Raumnummer```
darstellen zu können.
Grüße aus der Mathematik,
Matthias

**Comment by thenickless** [comment]
Umgesetzt in 3.3.5

Hi Matthias, nutze diesen Shortcode für deine Ausgabe:

`[univis task="mitarbeiter-alle" show="office" hide="telefon, mobile"]
`

Grüße, Benjamin
