### ISSUE TITLE
ICS-Link ermöglicht fremden Inhalt

### ISSUE THREAD

**Issue by mgmax** [RRZE-Webteam/rrze-univis#188]
Unter folgendem Link läd das RRZE zu einem kostenlosen Getränk ein ;-)

https://www.wordpress.rrze.fau.de/wp-content/plugins/rrze-univis/ics.php?summary=Freibier%20am%20RRZE

Wahrscheinlich wäre WP-Nonce die passende Abhilfe: https://codex.wordpress.org/WordPress_Nonces

**Comment by thenickless** [comment]
Hi Max, Danke für die Erheiterung! :-D Es wird bei deinem Hack jedoch kein .ics generiert, sondern ein File ohne Extension mit ein paar Defaultwerten ohne Bezug zum RRZE (außer jemand macht sich die Mühe herauszufinden, was der PRODID Wert bedeutet), das lediglich in einem Texteditor gelesen werden kann. Oder siehst du darin ein Sicherheitsproblem? Grüße, Benjamin

Inhalt:

BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//FAU//Webteam v1.0
CALSCALE:GREGORIAN
BEGIN:VTIMEZONE
TZID:Europe/Berlin
TZURL:http://tzurl.org/zoneinfo-outlook/Europe/Berlin
X-LIC-LOCATION:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
DTSTAMP:20220317T125912
UID:62332290ef879@fau.de
SUMMARY:Freibier am RRZE
DESCRIPTION:
DTSTART;TZID=Europe/Berlin:20220321T000000
DTEND;TZID=Europe/Berlin:20220321T000000
RRULE:FREQ=WEEKLY;INTERVAL=1;UNTIL=20220317T000000;WKST=MO;BYDAY=MO,TU,WE,TH,FR
END:VEVENT
END:VCALENDAR

**Comment by thenickless** [comment]
Hi Max, derzeit entwicklen wir ein neues Plugin rrze-campo, das die bisheringen UnivIS-basierten Plugins ablösen wird. Deinen Einwand habe ich dort aufgenommen und werde die ICS in WordPress intergriert umsetzen, d.h. mit nounces - Danke nochmals für deinen Bugreport. RRZE-UnivIS wird während der Übergangszeit nur bei kritischen Fehlern weiter entwickelt.

**Comment by xwolfde** [comment]
Und wo soll ich nun meine Cola Light herbekommen!??
