### ISSUE TITLE
Fehlermeldung "Konnte Lehrveranstaltungen nicht finden." um angegebene ID erweitern

### ISSUE THREAD

**Issue by csw-** [RRZE-Webteam/rrze-univis#19]
Die Fehlermeldung "Konnte Lehrveranstaltungen nicht finden." (und ggf. andere) sollten um den vom User angegebenen Wert erweitert werden um eine Zuordnung zu ermöglichen. Bsp: "Konnte Lehrveranstaltungen nicht finden. (123456789)"

Gerade bei Seiten mit mehreren LV-Einbindungen verliert man hier den Überblick, bzw. ist erst gar keiner geboten. (siehe Anhang) 
![univis-id](https://cloud.githubusercontent.com/assets/6545158/18385100/ca170428-768e-11e6-80f2-c806bf07bd24.png)

**Comment by endv02** [comment]
Ist drin ab Version 1.2.5

**Comment by csw-** [comment]
Perfekt. Vielen Dank!
