### ISSUE TITLE
Sortierung

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/rrze-univis#2]
Werden die Einträge nicht alphabetisch angezeigt? 

Wenn ich in Univis mir eine Institution anzeigen lasse, z. B. Lehrstuhl für Organische Chemie I ( http://univis.fau.de/form?__s=2&dsc=anew/tel&dir=nat/dchph/loc1&anonymous=1&ref=tel&sem=2015s&__e=483 , Link wird wohl nicht mehr gehen...), dann werden die Personen alphabetisch aufgeführt. 

Wenn ich über das Univis-Plugin die Einrichtung anzeigen lasse, werden die Personen nicht alphabetisch angezeigt: http://chem.nat.fau.de/department/personen-a-z/ 

Wie kann ich diese Einträge alphabetisch sortieren?

**Comment by endv02** [comment]
Das sollte normalerweise automatisch passieren, da gibt es wohl doch noch einen Bug, der eigentlich schon behoben schien... muss ich nochmal anschauen.

**Comment by endv02** [comment]
Sollte mit der neuesten Version behoben sein
7b485bd75987e100010a14939750f9306fdcf009
