### ISSUE TITLE
UnivIS-Default-Überschriften verständlich machen

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/rrze-univis#20]
Beispielseite: https://ithron.rrze.uni-erlangen.de/person/ludwig-fesenmeier/

Die Überschrift "es" bedeutet wohl "Examensseminar". Es wäre ganz fabelhaft, wenn Letzteres bei der Ausgabe da stünde, denn es sieht einfach besser aus.

**Comment by endv02** [comment]
Ist drin ab Version 1.2.5 (auch in der neuen Version von fau-person)
