### ISSUE TITLE
Warnings in PHP - hat sich die UnivIS API geändert?

### ISSUE THREAD

**Issue by thenickless** [RRZE-Webteam/rrze-univis#202]
(alle Warnings zu dem Zeitpunkt / alle gleiche Codezeile: https://matrix.to/#/!wyUpkRsFMDGzzGmxBf:fau.de/$kK4BDqtMnYcn-GtSaWBJgon2QV2s-Qclduj2s4K1ao8?via=fau.de )

PHP Warning:  file_get_contents(https://univis.uni-erlangen.de/prg?show=json&search=departments&number=111024): Failed to open stream: Connection timed out in /proj/cms/rrze/vhosts/cms.rrze.uni-erlangen.de/websource/wp-content/plugins/rrze-univis/includes/UnivISAPI.php on line 68
Warning: file_get_contents(https://univis.uni-erlangen.de/prg?show=json&search=departments&number=111024): Failed to open stream: Connection timed out in /proj/cms/rrze/vhosts/cms.rrze.uni-erlangen.de/websource/wp-content/plugins/rrze-univis/includes/UnivISAPI.php on line 68
PHP Warning:  foreach() argument must be of type array|object, bool given in /proj/cms/rrze/vhosts/cms.rrze.uni-erlangen.de/websource/wp-content/plugins/rrze-univis/includes/Shortcode.php on line 351
Warning: foreach() argument must be of type array|object, bool given in /proj/cms/rrze/vhosts/cms.rrze.uni-erlangen.de/websource/wp-content/plugins/rrze-univis/includes/Shortcode.php on line 351
PHP Warning:  file_get_contents(https://univis.uni-erlangen.de/prg?show=json&search=departments&number=111024): Failed to open stream: Connection timed out in /proj/cms/rrze/vhosts/cms.rrze.uni-erlangen.de/websource/wp-content/plugins/rrze-univis/includes/UnivISAPI.php on line 68

**Comment by xwolfde** [comment]
Bei number=420100 geht es und obiges liefert keine Daten.
Vermutlich kein problem mit der API, eher mit der Departmentnummer
