### ISSUE TITLE
Prüfen: bug oder hat sich die UnivIS-API wieder geändert?

### ISSUE THREAD

**Issue by thenickless** [RRZE-Webteam/rrze-univis#203]
(wäre nicht erstmalig)

Siehe
https://www.helpdesk.rrze.fau.de/otrs/index.pl?Action=AgentTicketZoom&TicketID=1081614

**Comment by xwolfde** [comment]
hatte sich am 14.3. wohl als was anderes erweisen. 
Wäre auch egal. UnivIS ist langfristig weg. Also machen wir hier nichts mehr.
