### ISSUE TITLE
Einbindung von Einzelpersonen bei identischem Vor- und Nachnamen

### ISSUE THREAD

**Issue by FlorianFiller** [RRZE-Webteam/rrze-univis#21]
Mit dem in der Doku angegebenen shortcode [univis task="mitarbeiter-einzeln" firstname="Max" lastname="Mustermann"] komme ich immer auf den "ersten" Max Mustermann - wie kann ich dem PlugIn erklären, dass ich gerne einen anderen Max Mustermann hätte?
Eine Eingrenzung durch number="123456789" im Shortcode funktioniert leider nicht und die OrgNr in den Einstellungen im Backend kann ich aufgrund anderer Unterseiten nicht enger fassen.

**Comment by endv02** [comment]
Da wird noch eine Erweiterung mit id="" eingebaut werden, wo die Personen-ID eingegeben werden kann.

**Comment by endv02** [comment]
Die einzelnen Mitarbeiter können ab Version 1.3.1 auch mit univisid="..." genau angegeben werden.
