### ISSUE TITLE
Problems with URL encoding/decoding

### ISSUE THREAD

**Issue by tamasgal** [RRZE-Webteam/rrze-univis#210]
We have a problem with the URLs generated for all the members. It seems that there is a problem with the URL handling in our setup and the commas are not treated correctly when decoding them.

Here is an example of the generated entry:

<img width="726" alt="Screenshot 2023-09-12 at 14 07 03" src="https://github.com/RRZE-Webteam/rrze-univis/assets/1730350/73aa6678-a98d-4613-a09d-9e3d82fd5373">

And here an example of such a URL which gives an "Error: Page not found":

https://web.test.ecap.work/index.php/institute/research-groups/astroparticle-physics/members/univisid/40086960_show=%2Ctelefon%2Cmail%2Csprungmarken%2Ccall&hide=

While when replacing the `%2C` character sets with `,`, the URL works:

https://web.test.ecap.work/index.php/institute/research-groups/astroparticle-physics/members/univisid/40086960_show=,telefon,mail,sprungmarken,call&hide=

What we do not understand is why this very same plugin is working on the RRZE site, since the URL is encoded in the very same way (`show=` is passed a list of strings which are separated by `,` encoded as `%2C` and obviously correctly decoded and interpreted by the plugin):

<img width="1068" alt="Screenshot 2023-09-12 at 14 08 23" src="https://github.com/RRZE-Webteam/rrze-univis/assets/1730350/7b7405a3-9c25-4867-9481-2d9a2d29f68d">

It is currently unclear to us at which stage the decoding fails. In PHP, or already at the webserver layer. Any hints are welcome!

We are currently using PHP 8.0.30 and Wordpress 6.2.2 via apache (it's the official `wordpress:6.2.2-apache` Docker image) behind an HAProxy load balancer.

**Comment by xwolfde** [comment]
Please dont spend too much time in this plugin - it wont be developed any longer and will soon get out of service/marked as archive only.

The educationalevents will come from Campo by the rrze-lectures plugin (if you want to try  it, please use the current dev version). Personal cards will be made by a new rrze-person plugin or a coming version and will get the personal data from the coming new adressbook from the IdM.

Therfor we wont spend any more time in this plugin.

**Comment by tamasgal** [comment]
OK, thanks.

Is there any timespan for those developments? We are currently moving our website to the new instance and this "bug" is  the last show-stopper. I guess we will simply patch it ourselves for now and incorporate the new plugins once they are released.

**Comment by xwolfde** [comment]
We are also waiting for the data from the API... but its more a management problem.

If you use FAU Person instead of the old UnivIS Plugin, its more likely that you can use it longer, cause we might add the new API-Sync there too.

**Comment by xwolfde** [comment]
By the way: Beneath the Campo- und the Adressbook Plugin our priority is currently to make all pluguins ready for PHP 8.1 (which has to be done till November) and to add Block Editor Support (so that we can allow the Block Editor for all sites at the end of the year).

For details, feel free to come to one of our open talks: https://www.rrze.fau.de/events/webmaster-sprechstunde/

**Comment by tamasgal** [comment]
I see `:)`

For the sake of completeness (in case anyone bumps into this), this function can be used as drop-in replacement in `templates/mitarbeiter-alle.php` for `http_build_query` meanwhile:

```php
// Same as http_build_query but without HTTP encoding
function custom_http_build_query($data) {
    $query = '';
    foreach ($data as $key => $value) {
        // Skip key-value pairs where the value is null
        if ($value !== null) {
            // Append the key and value, separated by '='
            $query .= $key . '=' . $value . '&';
        }
    }
    // Remove the trailing '&' if it exists
    if (!empty($query)) {
        $query = rtrim($query, '&');
    }
    return $query;
}
```
