### ISSUE TITLE
[enhancement] Sinnvollerer Titel als "Univisid" bei Mitarbeiter-Seiten

### ISSUE THREAD

**Issue by sebastian-schindler** [RRZE-Webteam/rrze-univis#211]
Die Seiten einzelner Mitarbeiter haben lediglich den Titel "Univisid" ohne Breadcrumb-Pfad, [z.B. hier](https://www.wordpress.rrze.fau.de/plugins/externe-daten-einbinden/rrze-univis/mitarbeiterdaten-einbinden/univisid/42192564_show=%2Ctelefon%2Cmail%2Csprungmarken%2Ccall&hide=/). In einer früheren Version des Plugins (v1.4.2) wurde der Pfad und Titel der aufrufenden Seite angezeigt, [z.B. hier](https://ecap.nat.fau.de/index.php/institute/research-groups/astroparticle-physics/members/univisid/40086960/).

Das alte Verhalten wäre insbesondere deswegen besser, weil ein typischer Website-Besucher nicht weiß, was "Univisid" zu bedeuten hat.

**Comment by xwolfde** [comment]
Korrekt. Das liegt aber nicht am Plugin, sondern den Wechsel in der Theme-Version.
Die Heroleiste mit der Breadcrumb wird in neuen Versionen des Themes als teil des Headers generiert und nicht mehr als Teil des Contents.
Dieses UnivIS-Plugin wird dafür nicht weiter aktualisiert, da das UnivIS-Plugin mit dem Ende von UnivIS nicht mehr weiterentwickelt wird und mittelfristig ausser Dienst genommen wird.
Stattdessen weren Lehrveranstaltungen zukünftig aus Campo geholt und Personendaten aus dem kommenden neuen Adressbuch-System im IdM.

Daher kann ich diesem Issue nur ein "Wont-Fix" geben,

**Comment by sebastian-schindler** [comment]
OK, danke - das macht Sinn. Ist ja eh nur ein "nice-to-have".
