### ISSUE TITLE
Keine alphabetische Sortierung bei Shortcut mitarbeiter-telefonbuch

### ISSUE THREAD

**Issue by lapmk** [RRZE-Webteam/rrze-univis#214]
Sowohl die Sprungmarkenliste als auch die Liste selbst werden beim Shortcut mitarbeiter-telefonbuch nicht alphabetisch sortiert.

Beispiel: https://www.physik.nat.fau.de/department/staff/

**Comment by thenickless** [comment]
fixed in 3.7.4
