### ISSUE TITLE
Übernahme englischer UnivIS-Einträge

### ISSUE THREAD

**Issue by FlorianFiller** [RRZE-Webteam/rrze-univis#23]
Das PlugIn übernimmt leider bei der Einbindung von Einrichtungen mithilfe des Shortcodes immer die deutschen Einträge/Funktionen - auch auf einer englischsprachigen Seite.
Kann ich das irgendwo einstellen/ändern?

Bei den (Einzel-)Kontakten funktioniert die automatische Übernahme der Informationen in der richtigen Sprache ja sehr gut!

**Comment by endv02** [comment]
Die Funktionalität ist bisher nicht eingebaut, wird aber im nächsten Update drin sein.

**Comment by mkuehnel85** [comment]
Hallo,
wir sind auch über dieses Problem gestolpert und haben in der Zwischenzeit eine leichte Modifikation des Plugins vorgenommen: Der Suffix für das description-Feld kann nun in den Einstellungen angegeben werden. Im Falle dass unsere Modifikation hilfreich ist, haben wir den Patch (als GIT diff) hier angehängt.
Beste Grüße aus Bamberg
[patch.txt](https://github.com/RRZE-Webteam/rrze-univis/files/868288/patch.txt)

**Comment by endv02** [comment]
Vielen Dank für den patch. In der neuesten Version ist jetzt die Unterstützung der englischen Ausgaben mit drin. Voraussetzung dafür ist zum Teil natürlich, dass diese von den UnivIS-Beauftragten auch mit eingepflegt werden.
