### ISSUE TITLE
Telefonnummern

### ISSUE THREAD

**Issue by FlorianFiller** [RRZE-Webteam/rrze-univis#24]
Das Plugin verhält sich bei der Einbindung von Organisationen bei der Anzeige von Telefonnummern "sonderbar".

shortcode: [univis number="41183828"]

Anzeige im UnivIS (immer die Durchwahl-Nummer):
![univis_plugin_1](https://cloud.githubusercontent.com/assets/12810141/21226317/375f18ee-c2d5-11e6-953b-0bf8bd9f870a.png)

Anzeige auf der Homepage (mind. 4 verschiedene Formate):
![univis_plugin_2](https://cloud.githubusercontent.com/assets/12810141/21226324/3f1a1818-c2d5-11e6-9c0f-7f6b08190547.png)

**Comment by endv02** [comment]
Die andere Form in der UnivIS-Ausgabe liegt daran, dass hier ein Skript hinterlegt ist, das die Ausgabe "aufhübscht" (wobei hier ja nur die Durchwahlnummern angegeben sind und die "Vornummer" ja auch komplett fehlt). Beim Personenplugin werden ja die "wilden" Telefonnummerneingaben ja schon vereinheitlicht, das könnte man in diesem Plugin auch einbauen. Eine Eingabe wie "Tel. 22421 od. 29349" würde dabei aber auch genau so stehen bleiben, das müsste in UnivIS dann angepasst werden.

**Comment by endv02** [comment]
In der neuesten Version werden die Telefonnummern vereinheitlicht dargestellt. Da hierbei aber einzelne Sonderfälle evtl. durch das Vereinheitlichungsraster fallen (wie z.B. Tel. 22421 od. 29349) wäre es gut, die Ausgaben der Telefonnummern auf den eigenen Seiten zu überprüfen und ggf. durch den UnivIS-Betreuer korrigieren zu lassen.
