### ISSUE TITLE
Anordnung von LVs

### ISSUE THREAD

**Issue by endv02** [RRZE-Webteam/rrze-univis#25]
Wunsch von der Anglistik: Schön wäre auch, wenn man die LV innerhalb einer LV-Kategorie chronologisch anordnen könnte und die Namen der DozentInnen erscheinen würden.

**Comment by endv02** [comment]
Geht mit dem Wunsch #23 überein.

**Comment by thenickless** [comment]
Ist in V3 umgesetzt
