### ISSUE TITLE
Einzelne Daten aus Univis einbinden

### ISSUE THREAD

**Issue by anbininf12** [RRZE-Webteam/rrze-univis#27]
Ist es möglich, einzelne Daten (z.B. Ort und Zeit) einer Veranstaltung aus Univis in eine Seite einzubinden?

**Comment by endv02** [comment]
Aktuell noch nicht. Werde ich mal genauer anschauen, ob sich das irgendwie sinnvoll realisieren ließe... in welchem Zusammenhang würde das denn benötigt werden?

**Comment by anbininf12** [comment]
Wenn man auf einer Seite automatisch Ort und Zeit einer Veranstaltung anzeigen lassen möchte.

**Comment by endv02** [comment]
Ab Version 1.3.1 erfolgt die Einzeldarstellung der Lehrveranstaltungen nicht mehr durch einen Link auf UnivIS, sondern gleich innerhalb des Webauftritts. Damit hat das Ganze schon ein schöneres Gesicht... die Anzeige nur einzelner Daten wird daher erstmal nicht erfolgen.
