### ISSUE TITLE
Fehlerhafte Überschrift in Auflistung der Lehrveranstaltungen

### ISSUE THREAD

**Issue by fapfa** [RRZE-Webteam/rrze-univis#29]
Hallo zusammen,
ich wollte soeben per Shortcode alle Lehrveranstaltungen auf unserer Wordpress-Seite ausgeben. Da ist mir folgender Fehler aufgefallen:
Die Masterseminare werden unter der Überschrift "MAufbauseminar (AS)terseminar (MAS)" geführt.
Das ist bestimmt ein Flüchtigkeitsfehler im Programmcode, denn ich kenne nur "Aufbauseminare (AS)" und "Masterseminare (MAS)" ;-)

Hier ein Screenshot der Preview:
![image 5](https://cloud.githubusercontent.com/assets/17494971/23748273/3174fbbc-04c3-11e7-8635-16ee9bf22c6c.png)
#

**Comment by endv02** [comment]
Ist in der Version 1.3.1 korrigiert
