### ISSUE TITLE
Fehlerausgabe bei manchen UnivIS Org Nr.

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/rrze-univis#3]
http://test5.wordpress.webhummel.rrze.uni-erlangen.de/forschung/
Auf dieser Siete habe ich 3 UnivIS eingefügt. Bei dem 3. (sollte eigentlich unter dem 2. ___________ stehen, hat er eine Fehlermeldung, die nach oben gezogen wird. 

Es betrifft die Org. Nr. 111025

Wie kann man überprüfen, dass dahinter auch wirklich Daten stecken, und nicht eine Fehlermeldung ausgegeben wird? Bzw. wie verlässlich wird UnivIS gepflegt? 

BTW: Evtl. auch im Ho To den Link angeben, wie man Dinge findet... also http://vorlagen.fau.de/anwendungen/univis/suche-einrichtungen.shtml?doform=1&suche=philosophie&show_persons=1&show_meta=1# z. B.

**Comment by endv02** [comment]
Wie verlässlich UnivIS gepflegt wird weiß nie jemand, deshalb muss man so viele Fehler wie möglich abfangen...

**Comment by endv02** [comment]
Sollte mit 134d021c75ddec0848414b78c7b67874239f0903 gefixed sein, kommt eine Fehlermeldung wenn die Org-Einheit keine Mitarbeiter enthält.
