### ISSUE TITLE
Fehler in README.md + Formatierung

### ISSUE THREAD

**Issue by rathsky** [RRZE-Webteam/rrze-univis#30]
Für einige Shortcodes wird id= angegeben, sollte aber wohl number= sein?

Generell wär's besser der Datei eine brauchbare Formatierung zu geben, [sowas wie](http://www.tablesgenerator.com/markdown_tables):

| Shortcode | Wirkung | seit Version |
|----------------------------------------------------------------------|--------------------------------------------------------------------------------------|--------|
| [univis task="lehrveranstaltungen-alle" id="21101522" type="vorl"] | alle Vorlesungen der Org-Nr. 21101522 (Kürzel wie im UnivIS) | 1.2.1 |
| [univis task="lehrveranstaltungen-alle" id="49680223" lv_import="0"] | blendet alle importierten Lehrveranstaltungen aus, um doppelte Ausgaben zu vermeiden | 1.2.6 |

Die Plugin-Seite im [RRZE-WordPress](https://www.wordpress.rrze.fau.de/plugins/rrze-univis/) scheint dazu nicht mehr aktuell zu sein.

**Comment by endv02** [comment]
Anleitung wird in Kürze entweder im Blog oder im WordPress-Handbuch (oder irgendwie in beidem) auf den neuesten Stand gebracht und übersichtlicher gemacht.
