### ISSUE TITLE
Bei type= optional Überschrift weglassen

### ISSUE THREAD

**Issue by rathsky** [RRZE-Webteam/rrze-univis#31]
Wäre schöner, bspw. will ich unsere Veranstaltungen im Akkordeon darstellen,  bei dem die Überschrift eh bereits in dessen Eintragsname steht.

Dazu hat die Überschrift im UnivIS noch ein unnützes Kürzel hinten dran, bspw. "Proseminar (PS)".

**Comment by endv02** [comment]
Werde ich noch einbauen.

**Comment by endv02** [comment]
Ab Version 1.3.4 über hide="lv-typ" bei task="lehrveranstaltungen-alle" ausblendbar
