### ISSUE TITLE
Auswahl Mitarbeiter in einer bestimmten Rolle

### ISSUE THREAD

**Issue by rathsky** [RRZE-Webteam/rrze-univis#32]
Wäre praktisch wenn Mitgliederlisten einer Orga auf solche in einer bestimmten Rolle (Lehrbeauftragte, Professoren etc.) gefiltert werden könnte.

**Comment by endv02** [comment]
Ab der nächsten Version gibt es für task="mitarbeiter-alle" die Möglichkeit, mit dem zusätzlichen Parameter zeige_jobs="Sekretariat" (mehrere Rollen durch Kommata getrennt) nur die Personen dieser Jobs ausgeben zu lassen. Der Wert muss dann genauso eingetragen werden wie in UnivIS hinterlegt, bitte auch bei englischer Ausgabe beachten, hier müssen dann auch die englischen Begriffe angegeben werden.
