### ISSUE TITLE
Studentische Arbeiten aus UnivIS abbilden

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/rrze-univis#33]
Während der Schulung heute kam die Frage, ob die studentischen Arbeiten, die sorgsam in UnivIS eingepflegt wurden auch über das UnivIS Plugin in WordPress angezeigt werden können. Zur Zeit wird das über eine Datenbank des Kunden gelöst, also:

UnivIS -> Datenbank -> Homepage. 

Sehen kann man das Ergebnis hier: http://www.leb.eei.uni-erlangen.de/lehre/arbeiten/index.php

Oder soll das in Zukunft auch alles über CRIS gehen?

**Comment by xwolfde** [comment]
Momentan haben wir das nicht.

Die Entwicklungsplanung von CRIS ist mir unbekannt
