### ISSUE TITLE
Stellenangebote aus UnivIS auf die Homepage bringen

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/rrze-univis#34]
In der Schulung heute kam die Frage auf, ob es möglich sei, die Stellenangebote, die man in UnivIS eingegeben hat, auch mit dem UnivIS-Plugin auf die Homepage bekommen kann. Diese Frage gebe ich gleich weiter.

**Comment by xwolfde** [comment]
Im Moment ist dies nicht möglich.

**Comment by endv02** [comment]
Wird jetzt über eine andere Lösung außerhalb dieses Plugins realisiert werden.
