### ISSUE TITLE
Parameter bei der Einbindung von Lehrveranstaltung

### ISSUE THREAD

**Issue by FlorianFiller** [RRZE-Webteam/rrze-univis#36]
Wir würden gerne - analog zur TechFak (http://www.tf.fau.de/studium/international/englische-lehrveranstaltungen.shtml) - für internationale Studierende nur englischsprachige Lehrveranstaltungen aus UnivIS importieren.

Dafür wären drei Dinge wünschenswert:
- Auswahlparameter "Sprache" (wie in UnivIS hinterlegt)
- Auswahlparameter "Semester" (wie in UnivIS hinterlegt)
- Modifikationsmöglichkeit der Standardansicht (idealerweise nur "Titel (Dozent)" mit hinterlegter Verlinkung auf die Lehrveranstaltung im UnivIS)

**Comment by endv02** [comment]
Die Semesterabfrage funktioniert jedenfalls schon mal: sem="2016w" (als Beispiel)

**Comment by FlorianFiller** [comment]
Ja, danke. Das habe ich mittlerweile in den geschlossenen Issues auch gefunden, es fehlt nur noch in der PlugIn-Beschreibung im Blog.
Die Auswahl der Sprache wäre aber ja für die beschriebene Funktionalität besonders wichtig.

**Comment by endv02** [comment]
Die Auswahl der Sprache wird in der nächsten Version (kommt nächste Woche) mit drin sein.

**Comment by endv02** [comment]
Die Auswahl der Sprache ist jetzt mit enthalten, über den Zusatzparameter sprache="E" bzw. sprache="D" werden bei task="lehrveranstaltungen-alle" nur die Veranstaltungen ausgegeben, bei denen die entsprechende Sprache hinterlegt ist.
Bei der Darstellung gehen die Wünsche auseinander, wie das am besten auf einen Nenner zu bringen ist ist noch unklar.

**Comment by FlorianFiller** [comment]
Ergänzend: 
Mir ist nicht ganz klar, welche Informationen/Parameter aus UnivIS übernommen werden und welche nicht - manchmal ist das Ergebnis sehr ähnlich, manchmal nicht. Untenstehend ein Beispiel für eine recht große Abweichung, die dann auch (mangels Information) für Probleme/Nachfragen bei der Anmeldung etc. sorgt.
![csr_univis](https://user-images.githubusercontent.com/12810141/28008322-5fe4429c-6557-11e7-92b7-554c2f857170.png)

![csr_plugin](https://user-images.githubusercontent.com/12810141/28008335-64a2db54-6557-11e7-9396-1698bebd046a.png)

**Comment by thenickless** [comment]
2DO:

"show" und "hide" um alle anderen Parametern wie ETCS-Credits & Co erweitern
