### ISSUE TITLE
Anzeige aus UnivIS wird nicht richtig geparst

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/rrze-univis#37]
Auf der Seite https://laserphysik.cms.rrze.uni-erlangen.de/forschung/publikationen-2/ (ganz unten) wird die Information aus UnivIS wohl nicht richtig geparst; UnivIS Id ist 1415121200. Heraus kommt dieses:

{{#years}}
{{title}}

    {{#data}}
    {{#authors}} {{#author}} {{#pkey}} {{#full-profile}} {{lastname}}, {{firstname}}; {{/full-profile}} {{^full-profile}} {{name}}; {{/full-profile}} {{/pkey}} {{/author}} {{/authors}}
    {{pubtitle}}
    {{#journal}} In: {{journal}} {{#volume}}{{volume}}{{/volume}} ({{year}}), S. {{pages}} {{#doi}}
    [DOI: {{doi}}]{{/doi}} {{#puburl}}
    [URL: {{puburl}}]{{/puburl}} {{/journal}} {{#booktitle}}{{^conference}} In: {{#editors}}{{#editor}}{{#pkey}}{{lastname}}{{/pkey}}{{/editor}} (Hrsg.): {{/editors}}{{booktitle}}.
    {{#plocation}}{{plocation}} : {{/plocation}}{{publisher}}, {{year}}, S. {{pages}}. {{#doi}}
    [DOI: {{doi}}]{{/doi}} {{#puburl}}
    [URL: {{puburl}}]{{/puburl}} {{/conference}}{{/booktitle}} {{#conference}}{{^booktitle}}{{^publisher}} Vortrag: {{conference}}{{#school}}, {{school}}{{/school}}
    {{#address}}{{address}}, {{/address}}{{#hsyear}}{{hsyear}}.{{year}}{{/hsyear}}{{^hsyear}}{{year}}{{/hsyear}} {{#doi}}
    [DOI: {{doi}}]{{/doi}} {{#puburl}}
    [URL: {{puburl}}]{{/puburl}} {{/publisher}}{{/booktitle}}{{/conference}} {{#conference}}{{#booktitle}} {{#organizer}} In: {{organizer}} (Veranst.): {{/organizer}} {{^organizer}} {{#editors}}In: {{#editor}} {{#pkey}}{{lastname}}; {{/pkey}} {{/editor}} (Hrsg:){{/editors}} {{/organizer}} {{booktitle}}
    ({{conference}}, {{address}}{{#hsyear}}, {{hsyear}}{{/hsyear}})
    {{#plocation}}{{plocation}} : {{/plocation}}{{#publisher}}{{publisher}}, {{/publisher}}{{year}}{{#pages}}, S. {{pages}}.{{/pages}} {{#series}}
    ({{series}}{{/series}}{{#servolume}} Bd. {{servolume}}{{/servolume}}{{#series}}){{/series}}{{#isbn}} - ISBN {{isbn}}{{/isbn}} {{#doi}}
    [DOI: {{doi}}]{{/doi}} {{#puburl}}
    [URL: {{puburl}}]{{/puburl}} {{/booktitle}}{{/conference}} {{^journal}}{{^booktitle}}{{^conference}}{{^school}}{{^number}} {{#volume}}BD. {{volume}}. {{/volume}}{{#plocation}}{{plocation}} : {{/plocation}}{{#publisher}}{{publisher}}, {{/publisher}}{{year}} {{#series}}
    ({{series}}{{/series}}{{#servolume}} Bd. {{servolume}}){{/servolume}}
    {{#pages}}{{pages}} Seiten.{{/pages}}{{#isbn}} ISBN {{isbn}}{{/isbn}} {{#doi}}
    [DOI: {{doi}}]{{/doi}} {{#puburl}}
    [URL: {{puburl}}]{{/puburl}} {{/number}}{{/school}}{{/conference}}{{/booktitle}}{{/journal}} {{#school}}{{^conference}} {{#publisher}}{{#plocation}}{{plocation}} : {{/plocation}}{{publisher}}, {{year}}
    {{/publisher}} {{address}}, {{school}}{{#hstype}}, {{hstype}}{{/hstype}}{{#number}} ({{number}}){{/number}}, {{#hsyear}}{{hsyear}}{{/hsyear}}{{^hsyear}}{{year}}{{/hsyear}}. {{#series}}
    ({{series}}{{/series}}{{#servolume}} Bd. {{servolume}}){{/servolume}}
    {{#pages}}{{pages}} Seiten. {{/pages}}{{#isbn}}ISBN {{isbn}}. {{/isbn}}{{#issn}}ISSN {{issn}}{{/issn}} {{#doi}}
    [DOI: {{doi}}]{{/doi}} {{#puburl}}
    [URL: {{puburl}}{{/puburl}} {{/conference}}{{/school}} {{#conference}}{{#publisher}}{{^booktitle}} ({{conference}} {{address}} {{hsyear}})
    {{#plocation}}{{/plocation}} : {{plocation}}{{#publisher}}{{publisher}}, {{/publisher}}{{year}} {{#series}}
    ({{series}}{{/series}}{{#number}}, Nr. {{number}}{{/number}}{{#series}}.){{series}}{{/series}}
    {{#pages}}{{pages}} Seiten.{{/pages}}{{#isbn}} ISBN {{isbn}}.{{/isbn}}{{#issn}} ISSN {{issn}}{{/issn}} {{#doi}}
    [DOI: {{doi}}]{{/doi}} {{#puburl}}
    [URL: {{puburl}}{{/puburl}} {{/booktitle}}{{/publisher}}{{/conference}} {{#number}}{{^school}}{{^journal}} Schutzrecht {{number}} {{#hstype}}{{hstype}}{{/hstype}} ({{hsyear}}) {{/journal}}{{/school}}{{/number}}

    {{/data}} 

{{/years}}

**Comment by endv02** [comment]
Die Anzeige von UnivIS-Publikationen klappt leider momentan nicht (siehe Blogartikel https://blogs.fau.de/webworking/2017/04/04/neues-beim-wp-plugin-rrze-univis/), da andere Prioritäten wichtiger waren und die Umstellung sehr zeitintensiv ist - Publikationen sollen ja eh vermehrt aus CRIS übernommen werden. Wird aber auch in Bälde noch angepasst werden, wenn von Kunden noch benötigt.

**Comment by endv02** [comment]
Die Ausgabe wurde soweit angepasst, dass Autor und Titel jetzt ausgegeben werden.
