### ISSUE TITLE
Interne Lehrveranstaltungsseite

### ISSUE THREAD

**Issue by fkranz** [RRZE-Webteam/rrze-univis#38]
Das Verlinken auf die interne Seite für eine Lehrveranstaltung funktioniert nicht, wenn man einzelne Lehrveranstaltungen für eine Person importiert (zB auf der jeweiligen Mitarbeiterseite)

Aufgerufen aus der Liste alle Lehrveranstaltungen der Lehrstuhls:
https://lgdv.cms.rrze.uni-erlangen.de/lehre/lehrveranstaltungen/lv_id/21719718/
[univis task="lehrveranstaltungen-alle" type="vorl"]

vs Aufgerufen aus der Mitarbeiterwebseite (https://lgdv.cms.rrze.uni-erlangen.de/person/kai-selgrad/)
https://lgdv.cms.rrze.uni-erlangen.de/person/kai-selgrad/lv_id/21719718 
[univis task="lehrveranstaltungen-alle" dozentid="21000502"]

Eigentlich sollte doch beides den gleichen Link geben oder es sollten wenigstens beide Links funktionieren.

**Comment by endv02** [comment]
Danke für den Hinweis, in der nächsten Version (geht noch in dieser Woche online) funktioniert auch der Link auf der Personenseite.
