### ISSUE TITLE
Zur Info für die Ausgabe auf der Website http://vorlagen.fau.de/anwendungen/univis

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/rrze-univis#4]
Hier werden Umlaute nicht erkannt. Bei der Einbindung der Nummer in Wordpress werden diese aber richtig ausgelesen. 

Vielleicht hilft diese Info, vielleicht nicht ;-) Ist mir nur aufgefallen.

**Comment by endv02** [comment]
sind unterschiedliche Plugins, eines ist für Webbaukasten, eines für WordPress. Wo genau werden die Umlaute nicht erkannt?

**Comment by steffigebel** [comment]
Nicht bei Wordpress. Wenn man da was sucht, auf er website vorlagen.xxx.de, werden Umlaute nicht erkannt. Das ist aber nicht weiter schlimm. Was das aber für andere Dinge zb irgendwoanders einbinden, hat, wisst ihr, dachte ich. Oder ist das auch nur eine Ausgabe von einer Original-Datei/Oberfläche…?
--
Stefanie Gebel
Webmanagement
Friedrich-Alexander-Universität Erlangen-Nürnberg
Regionales RechenZentrum Erlangen (RRZE)
Martensstrasse 1, 91058 Erlangen, Germany
Tel. +49 9131 85-27033
stefanie.gebel@fau.de
www.rrze.fau.de

Von: endv02 <notifications@github.com<mailto:notifications@github.com>>
Antworten an: RRZE-Webteam/rrze-univis <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Freitag, 17. April 2015 15:10
An: RRZE-Webteam/rrze-univis <rrze-univis@noreply.github.com<mailto:rrze-univis@noreply.github.com>>
Cc: "Gebel, Stefanie" <stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de>>
Betreff: Re: [rrze-univis] Zur Info für die Ausgabe auf der Website http://vorlagen.fau.de/anwendungen/univis (#4)


sind unterschiedliche Plugins, eines ist für Webbaukasten, eines für WordPress. Wo genau werden die Umlaute nicht erkannt?
