### ISSUE TITLE
Ausgabe entspricht nicht Univis-Eintrag

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/rrze-univis#41]
Bei den Studienzuschusskommissionen werden in der Wordpress-Ausgabe die Vertretungen unter einem Punkt zusammengefasst. Dadurch sieht es so aus, als ob die Vertreter der student. Mitglieder den Vorsitzenden der Professoren im Verhinderungsfall vertreten würden. 

Siehe hier unter Studienzuschusskommission: https://www.nat.fau.de/fakultaet/gremien/gremien/ 

## Ausgabe in Wordpress

Lehreinheit Biologie
Vorsitz

    Prof. Dr. Klingler, Martin

Vertretung im Verhinderungsfall

    Prof. Dr. Winkler, Thomas
    Prof. Dr. Dietrich, Petra
    Klingberg, Tim
    Wittner, Jens

Professoren

    Prof. Dr. Burkovski, Andreas

Studierende

    Balaz, Barbara
    Kunert, Timo

## Ausgabe in Univis:

Vorsitz

Klingler, Martin 

Vertretung im Verhinderungsfall
Winkler, Thomas   

Professoren
Burkovski, Andreas
Vertretung im Verhinderungsfall
Dietrich, Petra

Studierende
Balaz, Barbara  
Kunert, Timo

Vertretung im Verhinderungsfall
Klingberg, Tim   
Wittner, Jens

**Comment by endv02** [comment]
Hm... das Plugin macht an der Stelle eigentlich genau, was es tun soll: alle Personen mit dem gleichen Job zusammenfassen und auf einmal ausgeben. Die UnivIS-Ausgabe geht da teilweise den anderen Ansatz, dass man die Inhalte der Reihe nach angeben kann und die auch in der Reihenfolge wieder ausgegeben werden. 

Bei den meisten Fällen funktioniert die Zusammenfassung nach Jobs auch gut, in diesem Fall leider nicht. Leider musste ich feststellen, dass sich für diesen aktuellen Einzelfall auch keine schnelle Lösung im Plugin realisieren lässt, zeitlich wäre hier bestenfalls eine mittelfristige Lösung machbar, wenn noch mehr Bedarf besteht.

Daher empfehle ich die Lösung über UnivIS, wie es schon bei der Frauenbeauftragten gemacht wird: bei dieser steht nicht "Vertretung im Verhinderungsfall", sondern "Frauenbeauftragte im Verhinderungsfall". Wenn die anderen Vertretungen ebenso angepasst werden, also alle anders heißen, z.B. "Professoren im Verhinderungsfall" und "Studierende im Verhinderungsfall" werden die Jobs nicht mehr zusammengefasst und die Lösung passt.
