### ISSUE TITLE
Bei Übungen werden auch Vorlesungen angezeigt

### ISSUE THREAD

**Issue by endv02** [RRZE-Webteam/rrze-univis#42]
vermutlich bei Verknüpfung von Vorlesungen zu Übungen

**Comment by rvdforst** [comment]
Ein neues Attribut "parent_lv" wurde für das UnivIS-Shortcode hinzugefügt, wodurch die verknüpften Lehrveranstaltungen (parent lectures) nicht angezeigt werden. Bspw.
[univis number="1512002300" task="lehrveranstaltungen-alle" type="ue" parent_lv="0"]
