### ISSUE TITLE
Unterschiede UnivIS - UnivIS-PlugIn

### ISSUE THREAD

**Issue by FlorianFiller** [RRZE-Webteam/rrze-univis#43]
Wir verwenden bei uns auf der Seite das PlugIn, um Lehrveranstaltungen einzelner Einheiten anzuzeigen, bspw.: [univis number="40765243" task="lehrveranstaltungen-alle" sem=2017w] um die Lehrveranstaltungen des Instituts für Politische Wissenschaft anzeigen zu lassen.
Allerdings werden hier mehr Lehrveranstaltungen angezeigt als bei der Ansicht direkt über das UnivIS (Einrichtung suchen -> Lehrveranstaltungen) - bspw. Vorlesungen der Wirtschaftswissenschaften ("Development Economics").
Woran könnte das liegen bzw. wie lässt sich das verhindert/kennzeichnen?

**Comment by FlorianFiller** [comment]
Es wäre schön, wenn sich das jemand mal ansehen könnte.
Vielen Dank!

**Comment by endv02** [comment]
Sorry, das hatte ich übersehen... Wenn ich exakt die gleiche Abfrage nach Lehrveranstaltungen zu der UnivIS-OrgNr 40765243 an UnivIS starte, erhalte auch identisch viele Veranstaltungen:
http://univis.uni-erlangen.de/prg?search=lectures&department=40765243&show=lshort
Von welcher Einrichtung möchten Sie denn die Lehrveranstaltungen anzeigen lassen?

**Comment by FlorianFiller** [comment]
Die Anzeige für das "Institut für Politische Wissenschaft" ergibt bei mir unterschiedliche Anzeigen, je nachdem ob ich den "Klick-Weg" über UnivIS oder den Weg über die Einrichtungs-ID wähle.

UnivIS-Link auf dem "Klick-Weg":
http://univis.uni-erlangen.de/form?__s=2&dsc=anew/lecture&lecture_zentr=1&anonymous=1&dir=phil/dsp/ipowi&ref=lecture&sem=2017w&__e=477

Auch bei dem von Ihnen angegeben Link (der die ID verwendet) sind einige als "Import" gekennzeichnete Veranstaltungen dabei, die ich über den "Klick-Weg" nicht erhalte.
Diese würde ich gerne auch beim Import über das PlugIn ausschließen.

**Comment by endv02** [comment]
Die importierten Veranstaltungen können über lv_import="0" ausgeblendet werden. Vielleicht ist ja das schon ausreichend?
Ansonsten könnte das Problem auch daran liegen, dass das Institut ja den Lehrstühlen übergeordnet ist und daher nochmal andere Zuordnungen der Lehrveranstaltungen stattfinden.

**Comment by FlorianFiller** [comment]
Vielen Dank, 
lv_import="0" hilft auf jeden Fall schon einmal weiter und "erwischt" fast alle Problemfälle.

**Comment by endv02** [comment]
Sehr gut! Soll ich konkret nochmal nach der Lösung eines anderen Falles suchen?

**Comment by FlorianFiller** [comment]
Die aktuellen Fälle lassen sich mit dem Ausblenden des Imports erst einmal gut lösen, wenn ich aber in einem Einzelfall an die Grenzen komme, melde ich mich gerne mit dem konkreten Fall wieder.

**Comment by endv02** [comment]
Alles klar, gerne!

**Comment by FlorianFiller** [comment]
Ich habe jetzt einen Fall gefunden, in dem lv_import="0" offensichtlich keine Wirkung zeigt - die Importe werden trotzdem angezeigt:
https://www.phil.fau.de/internationales/incoming-studierende/englischsprachige-lehrveranstaltungen/theater-und-medienwissenschaft-2/

Woran könnte das liegen?
