### ISSUE TITLE
PHP 7.0.19-1 fails with error

### ISSUE THREAD

**Issue by RosesTheN00b** [RRZE-Webteam/rrze-univis#45]
Running the plugin with php 7.0.19-1 rises an uncaught error:

> Fatal error: Uncaught Error: [] operator not supported for strings in /var/lib/wordpress/wp-content/plugins/rrze-univis-master/univis/class_univis.php:567 Stack trace: #0 /var/lib/wordpress/wp-content/plugins/rrze-univis-master/univis/class_univis.php(551): UNIVIS->sxi2array(Object(SimpleXMLIterator)) #1 /var/lib/wordpress/wp-content/plugins/rrze-univis-master/univis/class_univis.php(385): UNIVIS->xml2array('http://univis.u...') #2 /var/lib/wordpress/wp-content/plugins/rrze-univis-master/univis/class_univis.php(74): UNIVIS->_ladePublikationen() #3 /var/lib/wordpress/wp-content/plugins/rrze-univis-master/univis/class_controller.php(45): UNIVIS->ladeDaten() #4 /var/lib/wordpress/wp-content/plugins/rrze-univis-master/rrze-univis.php(474): univisController->ladeHTML() #5 /usr/share/wordpress/wp-includes/shortcodes.php(345): RRZE_UnivIS->univis(Array, '', 'univis') #6 [internal function]: do_shortcode_tag(Array) #7 /usr/share/wordpress/wp-includes/shortcodes.php(223): preg_replace_callback('/\\[(\\[?)(univis...', 'do_shortcode in /var/lib/wordpress/wp-content/plugins/rrze-univis-master/univis/class_univis.php on line 567

**Comment by endv02** [comment]
Wobei genau trat der Fehler auf?

**Comment by RosesTheN00b** [comment]
Bei allem, wo auf das Univis zugegriffen werden muss. 
Beispiel:
univisid  konfiguriert: 100105
[univis task="publikationen" show="errormsg" ]
Erreichbar mit Uni-VPN:
**http://lme63.informatik.uni-erlangen.de/wp/index.php/teaching/courses/**

**Comment by RosesTheN00b** [comment]
Hey :-)
habt ihr schon herhausgefunden woran es liegt?

**Comment by rvdforst** [comment]
Die neue Version des Plugins behebt diesen Fehler.
