### ISSUE TITLE
Ergänzen des Parameters show="kompakt"

### ISSUE THREAD

**Issue by endv02** [RRZE-Webteam/rrze-univis#46]
Auf Kundenwunsch soll eine reine Überschriftenlösung ermöglicht werden:

ich wollte in Wordpress alle Praktika und Seminare vom entspr. Sem.
einbinden, mit:
[univis task="lehrveranstaltungen-alle" type="pr" sem="2017w"]
Allerdings kommt da immer alles mit Uebungen, Uhrzeit und Raum etc.

Gibt es eine Art Tag für Kurzansicht?
Also nur die Überschrift = Name (mit Link)?
Sonst wird die Liste viel zu lang:
https://informatik-studium.cms.rrze.uni-erlangen.de/studierende/praktika-se[..]

Wird mittelfristig umgesetzt werden, ist im dev-Zweig bereits in Vorbereitung.

**Comment by wrathmann** [comment]
Habe show="kompakt" auspobiert. Geht gut, allerdings wird  type dann ignoriert. Wäre schon wenn beides geht.

**Comment by thenickless** [comment]
Siehe #36
