### ISSUE TITLE
Backend: Suchfunktionen einbauen: UnivIS-Id und Lehrveranstaltungen einer EInrichtung

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-univis#49]
Wir wollen die alte Suche bei 
http://www.webbaukasten.rrze.fau.de/anwendungen/univis/suche-einrichtungen.shtml
wegmachen. Dazu brauchen wir aber ein Ersatz.
D.h. es muss möglich sein, im Backend die EInrichtung zu suchen und die notwendige Id dann daraus zu finden.
Bonustask: Weitere Ids finden, wie bspw. die von Lehrveranstaltungen.

**Comment by thenickless** [comment]
Suche ist in Version 3 integriert:

a) unter Settings
b) In der Metabox beim Erstellen einer Page oder eines Posts

- Lehrveranstaltung
- Organsation 
- Person
