### ISSUE TITLE
Überschriften werden nicht mitgeliefert

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/rrze-univis#5]
Baut man via Shortcode UnivIS ein, so kommen zwar die Mitarbeiter etc, die man wie formulare.fau.de gesucht hat, aber die Zuordnungen fehlen. Ist das so, weil man davon ausgeht, dass man als Seitentitel die H1 wählt? 

Bei einigen ist das auch fehlerhaft (also Suchergebnis vs Auslieferungsdaten): ZB: Die Org.Nr 00000000 sollte eigtl laut Überschrift in formulare.fau.de die Dekane (welche, steht da nicht) liefern, es sind aber dort Mitglieder eines Teams der Geschäftsstelle Engergie. Nun ist die Frage, an welcher Stelle etwas falsch läuft ;-) Hat die Geschäftsstelle eine falsche Zuordnung vorgenommen, oder arbeitet das Plugin noch nicht so, wie es soll...

**Comment by endv02** [comment]
Auf höherer Ebene gibt UnivIS manchmal komische Ausgaben... bei der Suche nach der Org-Nr. am zuverlässigsten die Seite http://vorlagen.fau.de/anwendungen/univis/suche-einrichtungen.shtml verwenden. UnivIS-Ausgabe kann überprüft werden, indem man im Browser die Nummer hier eingibt (beispielhaft steht hier die 40761621):
http://univis.uni-erlangen.de/prg?search=departments&number=40761621

Die ganz große Überschrift wird nicht mit ausgegeben, das ist richtig, sondern nur die Funktionen und UnivIS-Überschriften.
