### ISSUE TITLE
Keine Telefonnummern im Telefonbuch-Format + Telefonbuch-Format für Wordpress-Kontakte

### ISSUE THREAD

**Issue by Albager** [RRZE-Webteam/rrze-univis#50]
Das Telefonbuch zeigt weder Telefonnummern noch Email-Adressen.
![univis_mitarbeiter-telefonbuch](https://user-images.githubusercontent.com/11389126/36945909-043d6be4-1fb5-11e8-966b-01068ebe2ea4.png)

Außerdem wäre es toll, wenn man die selbe Darstellung auch mit den Wordpress-Kontakten im [FAU-Person-Plugin](RRZE-Webteam/fau-person) zur Verfügung hätte (z.B. mittels Shortcode [kontakt category=“person“ format=“telefonbuch“] 
+ggf. die üblichen Parameter zur Modifizierung der Ausgabe - https://www.wordpress.rrze.fau.de/files/2016/06/Zusammenfassung-Shortcode-kontakt.pdf)

**Comment by endv02** [comment]
Ist ab Version 2.3.0 bei den Formaten task="mitarbeiter-telefonbuch", "mitarbeiter-alle" und "mitarbeiter-orga" über show="telefon, mail" einblendbar, die Telefonnummern bei task="mitarbeiter-alle" mit hide="telefon" ausblendbar.
