### ISSUE TITLE
Anzeige falscher Lehrveranstaltungen (falsche Zuordnung "Verantwortliche/Verantwortlicher" und "Dozent/in")

### ISSUE THREAD

**Issue by AndreasBlombach** [RRZE-Webteam/rrze-univis#52]
An unserem Lehrstuhl gibt es einige Kurse, die von mehreren Dozenten gehalten werden. In UnivIS ist dafür ein Verantwortlicher eingetragen, dazu die konkreten Einzelkurse mit den jeweiligen Dozenten.
Dies scheint nun zu Anzeigeproblemen zu führen, wenn man die Lehrveranstaltungen einzelner Dozenten mittels Plugin auf deren Personenseiten einbindet.

Am konkreten Beispiel (mir geht es um "Ling BM 2"):

So sieht es bei UnivIS aus, wenn man sich alle Lehrveranstaltungen einer unserer Dozentinnen anzeigen lässt (Ganslmayer, Christine):

| Kurs |   | Dozent |
| -- | -- | -- |
| Examenskurs-Linguistik: Deutsche Gegenwartssprache (Erlangen) [EXAM] UE; 2 SWS; ECTS: 2; LAFV; Modulnr. 75702 (LAG, RS); Mo, 10:15 - 11:45, KH 1.013; ab 16.4.2018 |   | Ganslmayer, Ch. |
| Ling AM: Syntax der deutschen Gegenwartssprache + Begleitseminar (Erlangen) (für LA und BA) [Ling AM] SEM; 4 SWS; ECTS: 10; LAFV; LAFN; BAC; Gasthörer; nur für Studierende ab dem 4. Fachsemester; Mi, 10:15 - 13:45, B 301 | PF BPT-BA-Deu ab 4 | Ganslmayer, Ch. |
| Ling BM 2: Einführungsseminar: Historische Sprachwissenschaft (Teil 2) + Analyseseminar 2 (Erlangen) [Ling BM 2] KU; 2 SWS; Di, 10:15 - 11:45, B 301 |   | Ganslmayer, Ch. |
| Ling BM 2: Einführungsseminar: Historische Sprachwissenschaft (Teil 2) + Analyseseminar 2 (Erlangen) [Ling BM 2] KU; 2 SWS; Di, 16:15 - 17:45, KH 1.013 |   | Ganslmayer, Ch. |
| Ling BM 2: Einführungsseminar: Historische Sprachwissenschaft (Teil 2) + Analyseseminar 2 (Nbg.) [Ling BM 2] KU; 2 SWS; Do, 11:30 - 13:00, U1.039 |   | Ganslmayer, Ch. |
| Ling BM 2: Einführungsseminar: Historische Sprachwissenschaft (Teil 2) + Analyseseminar 2 (Nbg.) [Ling BM 2] KU; 2 SWS; Do, 9:45 - 11:15, U1.039 |   | Ganslmayer, Ch. |

Auf der Personenseite (https://www.germanistik.phil.fau.de/person/ganslmayer-christine/) sieht es aber so aus:

Seminar (SEM)

    Ling AM: Syntax der deutschen Gegenwartssprache + Begleitseminar (Erlangen) (für LA und BA)

    nur für Studierende ab dem 4. Fachsemester
        Mi 10:15-13:45, Raum B 301

Kurs (KU)

    Ling BM 2: Einführungsseminar: Historische Sprachwissenschaft (Teil 2) + Analyseseminar 2 (Erlangen)

    Kursveranstaltung im Rahmen von Ling BM 2, zusätzlich zur Plenumsveranstaltung Ling BM 2 (Teil 1) zu belegen
        Do 16:15-17:45, Raum B 301
        Di 10:15-11:45, Raum B 301
        Di 16:15-17:45, Raum B 301
        Di 16:15-17:45, Raum KH 1.013
    Ling BM 2: Einführungsseminar: Historische Sprachwissenschaft (Teil 2) + Analyseseminar 2 (Nbg.)

    Kursveranstaltung im Rahmen von Ling BM 2, zusätzlich zur Plenumsveranstaltung Ling BM 2 (Teil 1) zu belegen
        Do 11:30-13:00, Raum U1.039
        Fr 9:45-11:15, Raum U1.039
        Do 9:45-11:15, Raum U1.039
        Fr 11:30-13:00, Raum U1.039

Übung (UE)

    Examenskurs-Linguistik: Deutsche Gegenwartssprache (Erlangen)

    Modulnr. 75702 (LAG, RS)
        Mo 10:15-11:45, Raum KH 1.013

Bei den Kursen werden also auch Termine völlig anderer Dozenten angezeigt -- das ist natürlich ziemlich irreführend.
Ein Klick auf einen der Kurse (https://www.germanistik.phil.fau.de/person/ganslmayer-christine/lv_id/40450558/) zeigt ausschließlich den Kursverantwortlichen als Dozenten an, nicht aber die Einzeldozenten. Das Plugin scheint da also "Verantwortliche/Verantwortlicher" und "Dozent/in" zusammenzuwerfen.

**Comment by AndreasBlombach** [comment]
Ich möchte hier noch einmal nachhaken -- ist eine Änderung geplant/absehbar?

Der aktuelle Zustand hat dazu geführt, dass sich der Lehrstuhl nun dafür entschieden hat, die Lehrveranstaltungen überhaupt nicht mehr via Plugin einzubinden, sondern nur noch allgemein auf das UnivIS zu verweisen.
Das kann es doch auch nicht sein ...

**Comment by thenickless** [comment]
Ist im letzten Jahrtausend gefixt worden.
