### ISSUE TITLE
Error while activating in WordPress 4.9.5

### ISSUE THREAD

**Issue by michaeldorner** [RRZE-Webteam/rrze-univis#53]
While activating rrze-univis in WordPress 4.9.5 the error message 

<pre>The plugin generated 244 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.</pre>

occurred and I am not able to follow the links to the subpages of a lecture, for example. Any ideas how to fix this issue?

**Comment by xwolfde** [comment]
what tells the error log?

**Comment by xwolfde** [comment]
This is not an error log. I reefer to the error log of your webserver.

Which PHP version are you using? If its older than 7., please upgrade.

**Comment by michaeldorner** [comment]
We already use PHP7, and the log I have access is

<pre>[2018-04-24 18:02:05.892506] [info27] [warn] [php7] [84.39.77.255:54319] PHP Warning:  version_compare() expects at least 2 parameters, 0 given in /proj/websource/docs/FAU/fakultaet/techfak/www.oss.tf.fau.de/websource/osr/wp-content/plugins/rrze-univis-master/rrze-univis.php on line 47</pre>

**Comment by xwolfde** [comment]
danke, das hilft. muss beim debugging übersehen worden sein.

**Comment by rvdforst** [comment]
Dieses Problem ist bereits gelöst.
