### ISSUE TITLE
Einstellungsmöglichkeiten verschwunden

### ISSUE THREAD

**Issue by michaeldorner** [RRZE-Webteam/rrze-univis#54]
In der [Dokumentation](
https://www.wordpress.rrze.fau.de/administration/startseite-fakultaet/) ist beschrieben, wie man den "Sortierungs-Tag" ändern kann. Leider gibt es die Optionsseite nicht mehr. 

![Beiträge auf der Startseite](https://www.wordpress.rrze.fau.de/files/2015/05/design_theme_options_template.png)

**Comment by xwolfde** [comment]
Die Dokumentation ist da noch nicht aktuell. Mit der letzten Version des Themes sind alle Einstellungen in den Customizer gewandet.
Dort finden sich alle Einstellungen und man kann deren Änderungen "live" testen.
