### ISSUE TITLE
Format der Ausgabe manuell festlegen?

### ISSUE THREAD

**Issue by nneuss** [RRZE-Webteam/rrze-univis#59]
Gibt es vielleicht eine Möglichkeit, das Format der Ausgabe eines UnivIS-Plugin selber festzulegen.   Ich denke dabei an einen Formatstring mit HTML-Markup, wie zum Beispiel

[univis task="mitarbeiter-einzeln" univisid="00000000" format="<tr><td>$name</td><td>$email</td></tr>"]

so dass man das Ergebnis in einer HTML-Tabelle verwenden könnte.

**Comment by nneuss** [comment]
Meine HTML-tags sind eliminiert worden.  Ich versuche es nochmal:
'[univis task="mitarbeiter-einzeln" univisid="00000000" format="<tr><td>$name</td> <td>$email</td></tr>"]

**Comment by nneuss** [comment]
Nochmal:
```[univis task="mitarbeiter-einzeln" univisid="00000000" format="<tr><td>$name</td><td>$email</td><tr>"]```

**Comment by endv02** [comment]
Aus Gründen der Barrierefreiheit sollte auf die Verwendung von Tabellen nach Möglichkeit verzichtet werden. Welche Darstellung soll den genau mit dieser Formatierung bewirkt werden bzw. für welchen Zweck soll es eingesetzt werden?

**Comment by nneuss** [comment]
Wenn die Daten tabellarisch sind, sind Tabellen auch bezüglich Barrierefreiheit das richtige Element. Natürlich sollten sie nicht zum Layout verwendet werden.
Was ich will ist einfach eine flexible Anzeige von Mitarbeitern, genau mit den Daten und Informationen die ich anzeigen will und so angezeigt wie ich es möchte.  Ob in einer Tabelle oder nicht ist eigentlich egal.  So eine benutzerdefinierte Formatierung ist doch eigentlich auch naheliegend und wird beispielsweise vom CRIS-Plugin zur Verfügung gestellt: https://www.wordpress.rrze.fau.de/plugins/fau-cris/erweiterte-optionen/

**Comment by thenickless** [comment]
Das Plugin umzubauen, dass es einen Shortcode-Bereich [univis-custom] ... [/univis-custom] gibt, ist möglich und wird auf die 2DO Liste aufgenommen.

**Comment by thenickless** [comment]
Das Plugin wurde von Grund auf neu entwickelt. Falls neben der umgesetzten Formatierung noch Bedarf an einer flexiblen Darstellung bestehen sollte, bitte ich, ein Issue dazu zu erstellen. Vielen Dank.
