### ISSUE TITLE
Zur Info: Fork mit einigen Anpassungen

### ISSUE THREAD

**Issue by sistlind** [RRZE-Webteam/rrze-univis#6]
Hallo,
ich wollte mich nur einmal melden, da ich für unser Institut lte.eei.uni-erlangen.de auch eine Wordpress-Seite aufbaue.
Hierfür habe ich ihre tolle Vorarbeit geforked und einige Anpassen vorgenommen:
https://github.com/sistlind/rrze-univis

Eventuell sind einige auch interessant für, zB die PHP Warnings oder doppelte Anzeige von Lehrveranstaltungen.
Für Fragen stehe ich gerne zur Verfügung: stefan.lindner@fau.de

Gruß Stefan Lindner

**Comment by xwolfde** [comment]
Cool :)
Mergerequests, Unterstützung oder Vorschlänge nehmen wir immer gern entgegen.
An der UnivIS-Sache sind wir aber auch noch stark dran. Wobei wir uns derzeit auf das fau-person Plugin konzentrieren.
