### ISSUE TITLE
Anzeige der Kurse bei Lehrveranstaltungen

### ISSUE THREAD

**Issue by wrathmann** [RRZE-Webteam/rrze-univis#63]
Hallo Web-Team,
bei der Verwendung von 
[univis task="lehrveranstaltungen-alle" univisid="40812381" type="ue" ]
auf der Seite 
https://wwwneu.math.fau.de/angewandte-mathematik-2/mitarbeiter/dr-wigand-rathmann/
werden alle Kurstermine angezeigt. Beim Klick auf den Kurstitel (Übungen zur Mathematik für Ingenieure D1: CBI, CEN, LSE, MWT, NT) wird nur noch der erste Kurs angezeigt,
https://wwwneu.math.fau.de/angewandte-mathematik-2/mitarbeiter/dr-wigand-rathmann/lv_id/40819192/
Kann dies durch eine Anzeigoption gefixt werden?
Danke für die Hilfe,
W. Rathmann

**Comment by endv02** [comment]
In unserer Umgebung funktioniert das. Unter welcher Plugin-, PHP- und WordPress-Version taucht der Fehler auf?

**Comment by wrathmann** [comment]
Wir nutzen:
Wordpress 4.9.8
PHP 7.2
RRZE Univis 2.2.3

**Comment by thenickless** [comment]
Fehler tritt in V3 nicht auf.
