### ISSUE TITLE
Formatierung von Links und Fettdarstellung wird nicht umgesetzt

### ISSUE THREAD

**Issue by endv02** [RRZE-Webteam/rrze-univis#64]
siehe Seminar Medizintechnik (http://univis.uni-erlangen.de/form?__s=2&dsc=anew/lecture_view&lvs=tech/IE/LEH/medsem&anonymous=1&founds=med/IDR/IDRLDR/bildam_9,///IPEP/LP/anaphy,///KPS/KPSLA/grundl,///OKPFE/LO/online,nat/dphy/IAP/pbmt1/bmtab,tech/FT/lpt/agmt,/laidm,///IE/LEH/bildge,/etechn,/medpho,/medsem,/pb,//LETE/prgeti,//LS/fosena,/kardio,///IMMD/IMMD5/audmtr,/audmtt,/audmtt_9,/mt,/mtru,/mttut,/mtu,///IW/LM/compna,/sembio,//LWGK/metguk,//LWWE/werkst_7&sem=2019s&__e=961)
Bei Einzeldarstellung wird ausgegeben, wie es in UnivIS eingegeben wird: 
Fettdarstellung: \*Themenvergabe in der Vorbesprechung am 12.04.18, 08:30 - 10:00 Uhr. Teilnahme ist obligatorisch!.\*
Links: [\*Anmeldung ab 15. März mit StudOn!\*] http://www.studon.uni-erlangen.de/cat84282.html

**Comment by thenickless** [comment]
UnivIS-Strukturelemente werden vollständig als HTML in V3 umgesetzt.
