### ISSUE TITLE
Einschränkung Publikationen

### ISSUE THREAD

**Issue by fkranz** [RRZE-Webteam/rrze-univis#65]
Gibt es eine Möglichkeit Publikationen nur bis zu einem bestimmten Jahr ausgeben zu lassen, weil alle neueren im CRIS eingepflegt sind?

**Comment by thenickless** [comment]
Umgesetzt in 3.1.19:

Es gibt ein neues optionales Attribut "since".

Beispiel:
`[univis task="publikationen" since="2016"]`
Angezeigt werden alle Publikationen seit 2016 in der Sortierung "neu" zu "alt".
