### ISSUE TITLE
Alphabetische Sortierung Organigramm

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/rrze-univis#66]
Die Ausgabe, die das Plugin auf `univis number="(Nummer)` liefert, ist nicht konsequent alphabetisch. Bitte prüfen, ob das behebbar ist.

Links auf Beispielseiten:

https://www.chemie.nat.fau.de/ak-steinrueck/mitarbeiterinnen-und-mitarbeiter/
https://www.chemistry.nat.fau.eu/steinrueck-group/group-members/

**Comment by xwolfde** [comment]
Das ist kein Bug, das ist so gewollt. Hier wird die exakte Reihenfolge zurückgegeben, wie sie vom UnivIS Bearbeiter der EInrichtung selbst im UnivIS gemacht wurde.
