### ISSUE TITLE
Sortierung schlägt fehlt

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-univis#67]
Bei dieser Ausgabe:
[univis number="070702"]
bzw auch 
[univis number="070702" task="mitarbeiter-alle"]

ist die erzeugte Orgaliste nicht korrekte sortiert.
Es sind einzelne Namen nicht Alphabetisch in ihrer Kategorie.
![chemie-orga](https://user-images.githubusercontent.com/1070669/62040389-d4ff8780-b1f9-11e9-9e2e-e4e1ffd0cc1c.jpg)
Hier z.B. die Namen Wechsler, Wittkämpfer, die vor Massiciot sind.

**Comment by thenickless** [comment]
Bug fixed with version 2.4.0
