### ISSUE TITLE
Sprechstunden mit importieren und anzeigen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-univis#71]
gerade für große EInrichtungen, die nicht mehrere Hundert Dozenten auch noch in Kontakte Plugin importieren können, wäre die Anzeige der SPrechstunden über Shortcode wichtig

**Comment by thenickless** [comment]
2DO:
show="sprechstunden"

**Comment by thenickless** [comment]
Umgesetzt in V3
