### ISSUE TITLE
Zeit/Ort n.V.: ändern in Zeit/Ort:

### ISSUE THREAD

**Issue by faurex** [RRZE-Webteam/rrze-univis#76]
In der Übersicht z.B. von [univis task="lehrveranstaltungen-alle" type="vorl" lv_type="0"] wird eine Lehrveranstaltung aufgerufen. Der Seite in Wordpress ist z.B.:  xyz.de/seite/lv_id/49657111/ In der Seite ist ein Punkt "Zeit/Ort n.V.:". Das n.V. (nach Vereinbarung) macht wenig Sinn, wenn eine genaue Zeit und Ort Angabe angezeigt wird, z.B.: Mo 14:15-15:45, Raum H5

**Comment by thenickless** [comment]
Gefixt in V3
