### ISSUE TITLE
Sortierung | Überliegende Module ausblenden

### ISSUE THREAD

**Issue by ej64ojyw** [RRZE-Webteam/rrze-univis#77]
Helpdesk-Wünsche:

1. Manuell einstellen, welche Elemente zuerst erscheinen. Z.B. Vorl, Übung, Tutorium

2. Die Möglichkeit überliegende Module auszublenden. Beispiel: Wenn man die Übersicht zu einem Mitarbeiter erstellt und eigentlich nur die Übung dargestellt werden soll, d.h. type="ue" gefiltert wird wird trotzdem die überliegende Vorlesung mit eingeblendet. 

Helpdesk mit mehr Info: http://go.fau.de/9orob

**Comment by thenickless** [comment]
1. fehlt -> attribute 
`order="vorl,ueb,tut"`


2. ist gefixt in V3

**Comment by thenickless** [comment]
Umgesetzt in 3.1.18 https://github.com/RRZE-Webteam/rrze-univis/commit/ff38f72a092a907ae15575667b3220ca6ca026bf

**Comment by thenickless** [comment]
Es gibt in Version 3 ein neues optionales Attribut "order":

Zeigt alle Lehrveranstaltungen an, gruppiert nach Typ in der Reihenfolge, wie in "order" angegeben. Lehrveranstaltungen mit einem Typ, der nicht in "order" angegeben ist, werden nicht ausgegeben. In diesem Beispiel werden die Tutorials nicht ausgeben:
[univis task="lehrveranstaltungen-alle" order="vorl,ueb"]
