### ISSUE TITLE
Formatierung auf mobilen Endgeräten

### ISSUE THREAD

**Issue by lms-BeFe** [RRZE-Webteam/rrze-univis#78]
Hallo, 
wenn ich z.B. die Seite https://www.lms.tf.fau.de/studium-und-lehre/lehrveranstaltungen/lv_id/20493996/ auf einem mobilen Endgerät aufrufe wird die Schrift bis zum Bildschirmrand dargestellt, kan man dieses Verhalten ändern?
![Mobil_unschoen](https://user-images.githubusercontent.com/64403571/80406845-fb576e00-88c4-11ea-8b73-1d94161f2127.png)

**Comment by xwolfde** [comment]
Danke für die Meldung

**Comment by xwolfde** [comment]
Wird im nächsten Rollout gefixt sein
