### ISSUE TITLE
Übersetzungsprobleme bei englischer Ausgabe

### ISSUE THREAD

**Issue by ej64ojyw** [RRZE-Webteam/rrze-univis#80]
Bei einigen Mitarbeitern werden besondere Funktionen (z.B. Univis-Beauftragte, Studienfachkoordinator etc.) oder spezielle Angaben zu Sprechstunden (in der Regel der Zusatz „nach Vereinbarung“ oder „um telefonische Anmeldung wird gebeten“) auf der englischen Homepage nicht übersetzt. Das Institut (Institute for educational science) und die Lehrstuhlbezeichnung (Übersetzung ist hier allerdings falsch) wird hingegen übersetzt. Zum besseren Verständnis hier ein Screenshot:
![image002](https://user-images.githubusercontent.com/58593037/81645984-cb62ab80-942a-11ea-8899-9ffd4290a209.jpg)

Verknüpftes Ticket: http://go.fau.de/9ou5v

**Comment by Blubbaa** [comment]
Wir haben dasselbe Problem, auf Nachfrage beim Univis Support wurde bestätigt, dass im Univis nur manche Felder zweisprachig angelegt werden können. Beispiel:
![univis](https://user-images.githubusercontent.com/10139960/85553867-ac0f8e80-b624-11ea-918d-2367f93a32ae.png)

Wenn das nicht in Univis gelöst wird / werden kann, käme ggfs. als Lösung in Frage, manuell eingegebenen Feldern der Kontaktseite Priorität gegenüber den Daten aus Univis zu geben.

**Comment by thenickless** [comment]
2DO:

Alle Shortcodes mehrsprachig testen:

- [ ] Deutsch
- [ ] Englisch
- [ ] eine Drittsprache

**Comment by thenickless** [comment]
V3 tested.
