### ISSUE TITLE
type=" " Sortierung kann zu unspezifisch sein

### ISSUE THREAD

**Issue by ej64ojyw** [RRZE-Webteam/rrze-univis#83]
Beispiel und Problem: 
type="mas" schließt auch Lehrveranstaltungen von type="mas-pg" mit ein.
Praktisch wäre eine Funktion, um nur die Lehrveranstaltungen mas ohne z.B. mas-pg anzeigen zu lassen.

**Comment by thenickless** [comment]
Bug ist mit Version 3 gefixt.
