### ISSUE TITLE
Lehrveranstaltungen für Nächstes Semester

### ISSUE THREAD

**Issue by Blubbaa** [RRZE-Webteam/rrze-univis#84]
Aktuell gibt es ja die Möglichkeit zur Semesterauswahl per Shortcode (#26) oder das aktuelle Semester anzuzeigen (default). Für Studenten ist generell immer das aktuelle und das zukünftige Semester interessant. Das wäre also auch der wohl meistgenutzte Usecase. Als Admin möchte ich aber ungern alle 6 Monate die Shortcodes auf der Homepage ändern.

Vielleicht könnte man mit einen neuen Parameter das aktuelle Semester +-1 einstellen.

**Comment by thenickless** [comment]
Eingeführt in Version 3: 

Das bisherige Attribut 'sem' bleibt erhalten. Ist 'sem' eine Zahl, so wird sie zum heutigen Jahr addiert bzw subtrahiert. 

Beispiel:
(jetzt ist SS2021) 

sem="2022s" => Sommersemester 2022
sem="2000w" => Wintersemester 2000
sem="-2" => Wintersemester 2019
sem="1" => Wintersemester 2021
sem="2" => Sommersemester 2022
sem="3" => Wintersemester 2022

**Comment by thenickless** [comment]
gefixt in V3 https://github.com/RRZE-Webteam/rrze-univis/commit/9a3ef49cb8f0e6f21969561b8993068337844471
