### ISSUE TITLE
lehrveranstaltungen-einzeln formatting (much space between items)

### ISSUE THREAD

**Issue by georg-schwarz** [RRZE-Webteam/rrze-univis#85]
I experienced lists being displayed with very large spaces after each line of text. 

I attached the original photo of UnivIS and the displayed data via `[univis task="lehrveranstaltungen-einzeln" lv_id="41756313" sem="2020w"]`

## Original on UnivIS:

![image](https://user-images.githubusercontent.com/28054628/88668036-655cfa80-d0e2-11ea-90d9-cce4b2d18257.png)

## After import via Wordpress Plugin:

![image](https://user-images.githubusercontent.com/28054628/88668144-87567d00-d0e2-11ea-8e37-7a12567f9cef.png)

## Request

It would be nice to have some nicer styling for the "lehrveranstaltungen-einzeln" template that kind of resembles the corporate styling of FAU or at least is similar to the one on UnivIS.

Thank's in advance!

**Comment by thenickless** [comment]
Please reopen issue. Your lecture is not available via UnivIS-API any longer. I've tested other lectures with the new version of this plugin (V3) and didn't get any display errors like yours.
