### ISSUE TITLE
Problem bei Darstellung des Titels von Einzelterminen einer Veranstaltung

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-univis#86]
Mail:

Diese Woche habe ich unser Wahlpflichtfach in UnivIS  für das WS 20/21 eingetragen, siehe link hier unten:

https://univis.uni-erlangen.de/form?__s=2&dsc=anew/lecture_view&lvs=med/OKP[..]

Seltsamerweise muss sich wohl beim (automatischen?) Import der Daten dieser 3-tägigen Veranstaltung  von UnivIS auf unsere Homepage ein Fehlerteufel eingeschlichen haben : siehe angehängten Screenshot der Homepage.
![grafik](https://user-images.githubusercontent.com/1070669/90881439-b8e8fe00-e399-11ea-8c3a-b87fd4912cc6.png)

Hier heißt es bei der Bezeichnung des Wahlpflichtfaches zum 1.Veranstaltungstag, den 27.11., wie folgt:

Einzeltermin am 27.11.2020 14:45-18:00, Raum Orthop. Poliklinik (Kurs MED 84651 GrundlArbeitsgemeinschaft (AG)en der klinischen und röntgenologischen
DiArbeitsgemeinschaft (AG)nOberseminar (OS)tik am Stütz- und BewegunGrundseminar (GS)apparat)

...bei allen weiteren Tagen (28. und 29.11.) ist die Bezeichnung der Veranstaltung richtig: "Grundlagen der klinischen und röntgenologischen
Diagnostik am Stütz- und Bewegungsapparat"

 Es gibt in UnivIS nur ein Eingabefeld für einen Titel für alle 3 Tage, deshalb ist es auch so merkwürdig, dass bei Termin 2 +3 die Bezeichnung richtig ist, nur nicht bei Termin

**Comment by thenickless** [comment]
Getestet mit 

`[univis task="lehrveranstaltungen-einzeln" lv_id="21718116"]
`
Bug tritt in Version 3 nicht auf.
