### ISSUE TITLE
Als Titel nur den ects Titel ausgeben

### ISSUE THREAD

**Issue by lms-BeFe** [RRZE-Webteam/rrze-univis#87]
Hallo, ich habe bei uns auf der Homepage das Problem, dass ich in der Englischen Seite, die Titel aus dem Univis in deutsch angezeigt bekomme. Wäre es hierfür möglich statt den Titel, den ects Titel auszulesen?
https://www.lms.tf.fau.eu/study-and-teaching/lectures/#sprungmarke2
![Englisch](https://user-images.githubusercontent.com/64403571/94420663-c0fc4080-0184-11eb-9028-6cc0b4966ce8.png)
![ects_univis](https://user-images.githubusercontent.com/64403571/94420678-c6598b00-0184-11eb-87c4-5a49c000bdd1.png)

Vielen Dank
Benjamin Feulner

**Comment by thenickless** [comment]
gefixt in V3 https://github.com/RRZE-Webteam/rrze-univis/commit/c3ffd79669e371e0b8ffccfc8b6f4f59660442c8

**Comment by thenickless** [comment]
Dies geschieht automatisisiert im Template lehrveranstaltungen-alle.php:

Wenn die Sprache nicht Deutsch ist, wird der ECTS Titel ausgegeben, sofern er vorhanden ist:

```
                if ($lang != 'de_DE' && !empty($veranstaltung['ects_name'])){
                    $veranstaltung['title'] = $veranstaltung['ects_name']; 
                }else{
                    $veranstaltung['title'] = $veranstaltung['name'];
                }
```

Können Sie die gewünschte Darstellung mit den gegebenen Möglichkeiten erzielen? 
[https://www.wordpress.rrze.fau.de/plugins/fau-und-rrze-plugins/rrze-univis/](https://www.wordpress.rrze.fau.de/plugins/fau-und-rrze-plugins/rrze-univis/)

Falls nicht, zögern Sie bitte nicht, ein Issue zu schreiben. Das Plugin wurde kürzlich komplett neu entwickelt und wird nach der längeren Pause wieder aktiv gepflegt.

**Comment by thenickless** [comment]
Es lag daran, dass Ihre Website auf de_DE_formal gestellt ist. Im Code wurde nur de_DE berücksichtigt. Der Fehler ist mit der soeben ausgespielten Version 3.2.41 behoben. Vielen Dank für Ihre leicht verständliche Fehlermeldung!

**Comment by lms-BeFe** [comment]
Ja sehr gut, dann läuft nun alles.
Vielen Dank!
