### ISSUE TITLE
Problem bei zwei Telefonnummern

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/rrze-univis#88]
Bei den Kolleg*innen, die zwei Telefonnummern haben, etwa weil sie zwei 50% Stellen haben, wird in manchen Fällen eine Lösung mit "oder" ins UnivIS eingegeben, z.B. "09131 85-26958 oder -70212"

"oder" wird aber auf fau.de rausgefiltert, sodass die Ausgabe wie im Beispiel-Screenshot ist.

Kann für "oder" eine Ausnahmeregel eingebaut werden? Vielleicht macht es Sinn noch "und" als Ausnahme einzubinden.

![Screenshot_Kontakt](https://user-images.githubusercontent.com/53909165/105850645-47fde000-5fe2-11eb-961e-da7863cd061e.jpg)

**Comment by xwolfde** [comment]
Der Eintrag im UnivIS ist falsch. Das Telefonnummernfeld ist nur für eine (1!) Nummer vorgesehen und nicht für Prosatexte.
Wer bei mehr als eine Nummer hat oder mehr als eine Adresse, muss das zweite (oder dritte) Adressfeld aktivieren und es dort eintragen:
![grafik](https://user-images.githubusercontent.com/1070669/105858854-b42d1380-5fe3-11eb-8fc9-b6b92e58f57c.png)

**Comment by AndiWebred** [comment]
Der zweite oder dritte Adresseintrag wird aber halt nicht auf fau.de ausgegeben: https://www.intern.fau.de/person/dr-sebastian-teichert/

**Comment by AndiWebred** [comment]
...was wie ich gerade festgestellt habe wohl schon seit 2018 bekannt ist. Warum du mir das mit dem zweiten Eintrag also als Lösung anbietest und dann das Label "wontfix" ergänzt, ist mir nicht ganz klar.

UnivIS gibt ja das "Prosa"-Wort "oder" auch mit aus und liefert es sogar an Wordpress. Das Plugin streicht es halt anscheinend raus. Eine Ausnahme für "oder" einzubinden, wäre doch eine gute und sinnvolle Lösung, bis geklärt ist, wie das mit den weiteren Adress-Einträgen gelöst werden kann.

Aber gut. Ich habe für das problem mit den weiteren Adress-Einträge ein eigenes Issue bei rrze-person angelegt.

**Comment by xwolfde** [comment]
Es ist ein wontfix, weil es ein Eingabe/Nutzungsfehler des UnivIS-Bearbeiters ist.
In dem Feld bei UnivIS hat keine Prosa was zu suchen. Prosa = alle Zeichen, die nicht zu den erlaubten Zeichen einer Telefonnummer gehören.  Das haut auch bei anderen Datenverwaltungssystemen dann schief.

Diese Fehleingaben sollte man daher nicht  durch Workarounds unterstützen und daher tun wir das auch nicht in unseren Plugins.
